### ISSUE TITLE
Cannot Abort/Rollback Transactions due to Context Sharing

### ISSUE THREAD

**Issue by henry-imprint** [awslabs/amazon-qldb-driver-go#121] opened 2022-10-27 17:16 UTC
**Background**
Although the QLDB driver has built-in retry policy, it does not support timeouts. In order to enforce shorter timeouts to slow transactions, we tried to use context with timeouts to control the retries. However, since the [passed-in context](https://github.com/awslabs/amazon-qldb-driver-go/blob/v2.0.2/qldbdriver/qldbdriver.go#L123) to `QLDBDriver#Execute` is also used to [abort/rollback transaction](https://github.com/awslabs/amazon-qldb-driver-go/blob/v2.0.2/qldbdriver/session.go#L117), transactions cannot be gracefully aborted/rollbacked. Some sample code:

```
type QLDBWrapper struct {
	qldbdriver.QLDBDriver
}

func (wrapper *QLDBWrapper) Execute(
	ctx context.Context, fn func(txn qldbdriver.Transaction) (interface{}, error)) (interface{}, error) {
	var  (
		result interface{}
		err error
	)
	retry := 0
	for retry < 3 {
		wTimeout, cancel := context.WithTimeout(ctx, 1 * time.Second)
		result, err = wrapper.QLDBDriver.Execute(wTimeout, fn)
		cancel()
		if !errors.Is(err, context.DeadlineExceeded) {
			break
		}
		retry++ // Abort for Execute will fail due to already deadline exceeded context. 
	}
	return result, err
}
```

**Request**
1. How can we instrument timeout via context with transaction abort correctly?
2. Can the driver provide timeout support with its retry policy?

**Comment by bwinchester** [comment] 2022-10-27 21:47
Have you checked out the retry and retry with backoff jitter pattern? 
https://docs.aws.amazon.com/qldb/latest/developerguide/driver-cookbook-golang.html#cookbook-golang.crud.retry-logic

**Comment by henry-imprint** [comment] 2022-10-28 03:36
> Have you checked out the retry and retry with backoff jitter pattern? 
> 
> https://docs.aws.amazon.com/qldb/latest/developerguide/driver-cookbook-golang.html#cookbook-golang.crud.retry-logic

We did, but the policy does not allow configuration of timeouts. With the default QLDB timeout being 10s+, we cannot preemptively abort transactions and force retry on our own with contexts or other means.

**Comment by bwinchester** [comment] 2022-10-28 04:02
> > Have you checked out the retry and retry with backoff jitter pattern?
> > https://docs.aws.amazon.com/qldb/latest/developerguide/driver-cookbook-golang.html#cookbook-golang.crud.retry-logic
> 
> We did, but the policy does not allow configuration of timeouts. With the default QLDB timeout being 10s+, we cannot preemptively abort transactions and force retry on our own with contexts or other means.

default QLDB timeout being 10s+? Is that just testing the 4 retry with the backoff function as it exists on the driver, or is there another timeout somewhere? Reason I ask, is I just merged a change on the jitter function that should reduce the total time on a transaction (when its hitting OCC conflicts or contention). ref: https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

If you implement your own jitter function in your code, which is a copy of the ExponentialBackoffStrategy function as it exists  off the master branch today, your total time waiting on a transaction should be cut down from 10s to < 1s. That is, the wait time added during backoff should be dramatically shorter, and practicing full jitter to allow for more writers to complete more quickly. Simply reference your own backoff function into the retryPolicy.Backoff property, rather than using the current drivers provided one.

https://github.com/awslabs/amazon-qldb-driver-go/blob/98165efe68b3de03d37ff4d522f19c68f92609de/qldbdriver/retry.go#L47

It's a subtle change, in the above referenced PR, but the backoff time should have been `SleepBase * 2 ** retryAttempt` but instead it was `SleepBase ** retryAttempt` . If your sleep base was 20ms, retries after the 2nd retry would always add 3 seconds of sleep.

**Comment by timmyimprint** [comment] 2022-11-08 03:08
There doesn't seem to be another timeout anywhere. How can you configure a first-time timeout? Say you want every operation to be limited to 5 seconds.

**Comment by bwinchester** [comment] 2022-11-08 16:00
We are working to to release a patch version which would drop the 10 seconds you observed down dramatically.

**Comment by timmyimprint** [comment] 2022-11-10 01:05
Ok, so to summarize. It seems like there is no way to do a custom timeout on any attempt. We can do the timeout on the client side, but then the client would have to do the retry and cannot do it successfully b/c the client does not know when the rollback of the first attempt has completed. Is there anyway around this? 

However, we can customize a jitter or delay between retries which should help our retry performance go from 3+ seconds to 1+ seconds, due to a bug in the default jitter calculation. Is this correct?

**Comment by bwinchester** [comment] 2022-11-10 19:12
> However, we can customize a jitter or delay between retries which should help our retry performance go from 3+ seconds to 1+ seconds, due to a bug in the default jitter calculation. Is this correct?

You can customize a backoff function if you have specific requirements, or test if the v3.0.1 release with the default backoff function improves client times with less sleep/wait between any retries.

**Comment by bwinchester** [comment] 2022-11-10 23:03
Hi @henry-imprint @timmyimprint ,

Let me know if this would work for you. You can use it with or without the backoff policy. You can define the number of retries. And if you wrap the context you use in the Execute function `context.WithTimeout(context.Background(), time.Duration(3000)*time.Millisecond)`, you can set a time duration. I've tested I can set the time duration to 100ms and the transaction aborts and is never committed to the database. When I bump the timeout to 3000ms, the transaction will succeed.

I modified the AWS go cookbook example:
```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/qldbsession"
	"github.com/awslabs/amazon-qldb-driver-go/v3/qldbdriver"
)

func main() {
	awsSession := session.Must(session.NewSession(aws.NewConfig().WithRegion("us-east-1")))
	qldbSession := qldbsession.New(awsSession)

	retryPolicy := qldbdriver.RetryPolicy{
		MaxRetryLimit: 4,
		Backoff:       qldbdriver.ExponentialBackoffStrategy{SleepBase: 20, SleepCap: 4000}}

	driver, err := qldbdriver.New(
		"DevLedger",
		qldbSession,
		func(options *qldbdriver.DriverOptions) {
			options.LoggerVerbosity = qldbdriver.LogInfo
			options.RetryPolicy = retryPolicy
		})
	if err != nil {
		panic(err)
	}
	defer driver.Shutdown(context.Background())

	ctx, cancelContext := context.WithTimeout(context.Background(), time.Duration(3000)*time.Millisecond)
	_, err = driver.Execute(ctx, func(txn qldbdriver.Transaction) (interface{}, error) {
		return txn.Execute("INSERT INTO Person {'firstName': 'Bob777', 'lastName': 'Doe', 'age': 77}")
	})
	if err != nil {
		fmt.Println("error tx")
		fmt.Println(err)
	}
	cancelContext()
}

```

**Comment by henry-imprint** [comment] 2022-11-11 01:08
@bwinchester We would still run into the issue where the timed out/canceled context will be used to send RPC calls to abort transaction with QLDB, and because the context is already timed out/canceled, we cannot reliably revert our txn, right? 

If I understand correctly, we will need to do the abort call with a different context. Or we could have transaction committed but application error out and should be reverted?

**Comment by bwinchester** [comment] 2022-11-11 06:29
@henry-imprint I updated the example to include `qldbdriver.LogDebug` level setting for the driver. I re-ran the sample code above and confirmed the driver is performing tryAbort in the session handler using the context for you. In debug log level it logs `Failed to abort the transaction` but I was able to confirm records either existing or not existing, depending on how long the timeout was. 

```
2022/11/10 23:56:34 [DEBUG] Creating a new session
2022/11/10 23:56:35 [DEBUG] &{<nil> <nil> <nil> <nil> <nil> [omitted] <nil> [omitted] {}}
2022/11/10 23:56:35 [DEBUG] &{<nil> <nil> <nil> [omitted] <nil> [omitted] <nil> <nil> {}}
2022/11/10 23:56:35 [DEBUG] &{0x1027b7e40 <nil> <nil> <nil> <nil> [omitted] <nil> <nil> {}}
2022/11/10 23:56:35 [DEBUG] **Failed to abort the transaction.**
Caused by 'operation error QLDB Session: SendCommand, context deadline exceeded'
2022/11/10 23:56:35 error: operation error QLDB Session: SendCommand, https response error StatusCode: 0, RequestID: , canceled, context deadline exceeded
```

**Comment by henry-imprint** [comment] 2022-11-11 16:31
@bwinchester Does it mean we can safely ignore the fact that QLDB "failed to abort"? I am concern if there could be a timing edge case where transaction is committed but something error out and needs aborting. Want to get a confirmation from the authors that transaction can be safely or deemed rolled back.

**Comment by bwinchester** [comment] 2022-11-14 17:48
hi @henry-imprint. I think this issue would be better addressed with a customer support engagement, where the QLDB team can work with you on your use case.  You can start the engagement process using the Contact AWS page, or in the QLDB golang driver page using the `Provide Feedback` link. Using customer support this way would allow us to understand your workflow better and provide some best practices for that use case.

[Contact AWS](https://aws.amazon.com/contact-us/)

[Link for the golang driver page](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.golang.html)

<img width="257" alt="image" src="https://user-images.githubusercontent.com/2374757/201729039-a8ef4ad4-4ef1-4b15-a659-e65f190f8729.png">

**Comment by allimn** [comment] 2022-11-22 01:45
Hi @henry-imprint , to engage with customer support, could you use the first link to [Contact AWS](https://aws.amazon.com/contact-us/)? Sorry for the inconvenience.

**Comment by bwinchester** [comment] 2023-01-05 20:26
Closing for no activity. Please reach out if you need help starting a support engagement.

**Closed by bwinchester** 2023-01-05 20:26 UTC
